__title__ = 'gainsay'
__description__ = 'Redis Notification Framework.'
__version__ = '0.1.0'
__author__ = 'David Janes'
__author_email__ = 'davidjanes@gmail.com'
# __license__ = 'MIT'
__url__ = 'https://github.com/lenderkey/gainsay'
